@TaskTrackerAPI_HostAddress = https://localhost:7217



GET {{TaskTrackerAPI_HostAddress}}/api/todoitems

###

POST {{TaskTrackerAPI_HostAddress}}/api/todoitems
Content-Type: application/json
{
  "title": "Task Name",
  "description": null,
  "dueDate": null,
  "isComplete": true
}
###

GET {{TaskTrackerAPI_HostAddress}}/api/todoitems/complete

###

DELETE {{TaskTrackerAPI_HostAddress}}/api/todoitems/5

###

GET {{TaskTrackerAPI_HostAddress}}/api/todoitems/4

###

PUT {{TaskTrackerAPI_HostAddress}}/api/todoitems/4
Content-Type: application/json
{
  "title": "Task Name UPDATED",
  "description": "SOMEWHAT Super Important Task",
  "dueDate": "2025-10-23T19:25:45+00:00",
  "isComplete": false
}
###
