@TaskTrackerAPI_HostAddress = https://localhost:7217

POST {{TaskTrackerAPI_HostAddress}}/todoitems
Content-Type: application/json
{
  "title": "Task Name",
  "description": "Super Important Task",
  "dueDate": "2025-10-23T19:25:45+00:00",
  "isComplete": false
}

###

GET {{TaskTrackerAPI_HostAddress}}/todoitems

###

GET {{TaskTrackerAPI_HostAddress}}/todoitems/3

###

PUT {{TaskTrackerAPI_HostAddress}}/todoitems/3
Content-Type: application/json
{
  "title": "Replacement Task",
  "description": "SuperER ImportantER Task",
  "dueDate": "2025-10-23T19:25:45+00:00",
  "isComplete": true
}
###

DELETE {{TaskTrackerAPI_HostAddress}}/todoitems/2

###
